### ISSUE TITLE
subtract-with-overflow or out-of-range panic decompressing invalid file

### ISSUE THREAD

**Issue by FauxFaux** [Frommi/miniz_oxide#19]
I've found and minified a file which causes the same symptoms as #13, but I don't think it's the same problem.

The file is pretty horribly invalid. Horribly, horribly invalid. Confuses the other tool I'm working on, too.

Test and data file:
https://github.com/FauxFaux/miniz_oxide/commit/0f3b4803e5cfe574a8d824f25e60b6c840dce2c7

```
thread 'inf_issue_13' panicked at 'attempt to subtract with overflow', miniz_oxide/src/inflate/core.rs:958:25
...
  10: miniz_oxide::inflate::core::decompress_fast
             at miniz_oxide/src/inflate/core.rs:958
  11: miniz_oxide::inflate::core::decompress_inner
             at miniz_oxide/src/inflate/core.rs:1347
  12: miniz_oxide::inflate::core::decompress
             at miniz_oxide/src/inflate/core.rs:1003
  13: miniz_oxide::inflate::decompress_to_vec_inner
             at miniz_oxide/src/inflate/mod.rs:93
  14: miniz_oxide::inflate::decompress_to_vec
             at ./src/inflate/mod.rs:61
  15: test::inf_issue_13
             at miniz_oxide/tests/test.rs:20
```

**Comment by oyvindln** [comment]
Ah, it seems we didn't check for the invalid length codes, so they resulted in a match length of 0, which broke things.
